services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    container_name: php_dev
    volumes:
      - ../../../app:/var/www/html
    #ports:
      #- "8080:80"
      #- "9003:9003"
    environment:
      - PHP_IDE_CONFIG=serverName=php_dev
    networks:
      - php_dev_network

volumes:
  app_data:

networks:
  php_dev_network:
    external: true