services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb_dev
    command: keydb-server --port 6379
    volumes:
      - ../../data/keydb:/data
    ports:
      - "6379:6379"
    networks:
      - php_dev_network

volumes:
  keydb_data:

networks:
  php_dev_network:
    external: true